# Generated by Django 6.0.2 on 2026-02-16 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parcels", "0002_parcel_climate_zone"),
    ]

    operations = [
        migrations.AddField(
            model_name="parcel",
            name="soil_drainage",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="parcel",
            name="soil_ph",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
