# Generated by Django 6.0.2 on 2026-02-18 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parcels", "0003_parcel_soil_drainage_parcel_soil_ph"),
    ]

    operations = [
        migrations.AddField(
            model_name="parcel",
            name="soil_source",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
