# Generated by Django 6.0.2 on 2026-02-18 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TreeSpecies",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scientific_name", models.CharField(max_length=200, unique=True)),
                ("common_name", models.CharField(max_length=200)),
                ("koppen_zones", models.JSONField(default=list)),
                ("soil_ph_min", models.FloatField()),
                ("soil_ph_max", models.FloatField()),
                ("drought_tolerant", models.BooleanField(default=False)),
                ("primary_use", models.CharField(max_length=20)),
                ("max_height_m", models.FloatField()),
                ("maintenance_level", models.CharField(max_length=20)),
                ("image_url", models.URLField(blank=True, max_length=500)),
                ("attributes", models.JSONField(default=list)),
            ],
            options={
                "verbose_name_plural": "tree species",
                "ordering": ["common_name"],
            },
        ),
    ]
