# Generated by Django 6.0.2 on 2026-02-10 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_customuser_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="experience_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("beginner", "Beginner"),
                    ("intermediate", "Intermediate"),
                    ("experienced", "Experienced"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="goals",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="customuser",
            name="maintenance_level",
            field=models.CharField(
                blank=True,
                choices=[("low", "Low"), ("medium", "Medium"), ("high", "High")],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="profile_completed",
            field=models.BooleanField(default=False),
        ),
    ]
